### ISSUE TITLE
Some good way

### ISSUE THREAD

**Issue by vb078** [automata/osc-web#12]
Hey ;)

I just found this http://www.tamats.com/blog/?p=339&cpage=1
This realy helped me.
But I dont understand how you reset sent message with it !
I realy noob on node. So, if you want to try and give me feedback its would be fresh for my new install...<br>
Thx for your great great work.

**Comment by automata** [comment]
Hello, sorry for the long hiatus! I tried to check the website but it's 404. Is is still an issue? If yes, please feel free to reopen it and give more details if you can. Thanks!
