### ISSUE TITLE
unhandled socket.io url

### ISSUE THREAD

**Issue by TranceGeniK** [automata/osc-web#3]
Hi,

I was testing osc-web-server and got this messages in my console : 

info  - unhandled socket.io url
warn  - unknown transport: "undefined"

I think i've done all right... How can I fix it ?

**Comment by automata** [comment]
Does this issue still? Do you have more details so I can try to reproduce here? Latest update is supposed to work.

**Comment by automata** [comment]
Closing this one for now, please feel free to reopen it if the issue stills. Thanks!
