### ISSUE TITLE
more like a question

### ISSUE THREAD

**Issue by transfluxus** [automata/osc-web#9]
how can I send values with an osc message?

**Comment by transfluxus** [comment]
should maybe be added to the examples:

socket.emit('message', {address:'/play',args:[
                {type:'string', value:'sent'},
                {type:'integer', value:2},
                {type:'float', value:2.4}]});

**Comment by boonier** [comment]
Holy moly -- yes it should be added to the examples! Spent hours playing around only to stumble across this..Was the solution from the socket.io docs?

**Comment by transfluxus** [comment]
one year ago... can't even remember what I used it for

**Comment by automata** [comment]
That's great! I'll add that as an example, thanks! I'm dusting off the project and will probably make it more a library/app to make it easier to use.

I'm also added the possibility to send messages with arguments like strings. For instance: `socket.emit('message', '/foo/bar 42 23')`.
